---
- name: zabbix login
  uri:
    url: "http://{{zabbix_server}}/zabbix/api_jsonrpc.php"
    method: POST
    body_format: json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "user.login",
        "params": {
          "username": "{{zabbix_web_user}}",
          "password": "{{zabbix_web_pass}}"
        },
        "id": 1
      }
    headers:
      Content-Type: application/json-rpc
    follow_redirects: safe
  register: auth_id


